config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :money_ins
  resources :money_outs
  resources :categories

  get "dashboard" => "dashboard#index"
  root to: "dashboard#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/money_in.rb
class MoneyIn < ApplicationRecord
  validates :label, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :money_date, presence: true

  belongs_to :category

  def self.ransackable_attributes(auth_object = nil)
    [ "amount", "category_id", "description", "label", "money_date" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "category" ]
  end
end

app/controllers/money_ins_controller.rb
class MoneyInsController < ApplicationController
  before_action :set_money_in, only: %i[ show edit update destroy ]

  # GET /money_ins or /money_ins.json
  def index
    @q = MoneyIn.includes(:category).ransack(params[:q])
    @pagy, @money_ins = pagy(@q.result.order(created_at: :desc))
    @categories = Category.all
  end

  # GET /money_ins/1 or /money_ins/1.json
  def show
  end

  # GET /money_ins/new
  def new
    @money_in = MoneyIn.new
  end

  # GET /money_ins/1/edit
  def edit
  end

  # POST /money_ins or /money_ins.json
  def create
    @money_in = MoneyIn.new(money_in_params)

    respond_to do |format|
      if @money_in.save
        format.html { redirect_to money_ins_path, notice: "Receita criada com sucesso.", status: :see_other }
        format.json { render :index, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @money_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /money_ins/1 or /money_ins/1.json
  def update
    respond_to do |format|
      if @money_in.update(money_in_params)
        format.html { redirect_to money_ins_path, notice: "Receita atualizada com sucesso.", status: :see_other }
        format.json { render :index, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @money_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /money_ins/1 or /money_ins/1.json
  def destroy
    @money_in.destroy!

    respond_to do |format|
      format.html { redirect_to money_ins_path, notice: "Receita excluída com sucesso.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_money_in
      @money_in = MoneyIn.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def money_in_params
      params.expect(money_in: [ :label, :description, :amount, :money_date, :category_id ])
    end
end

app/helpers/money_ins_helper.rb
module MoneyInsHelper
end

app/views/money_ins/_form.html.erb
<%= form_with(model: money_in) do |form| %>
  <% if money_in.errors.any? %>
    <div style="color: red">
      <ul>
        <% money_in.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :label, class: "form-label", for: "moneyInLabel" %>
    <%= form.text_field :label, class: "form-control", id: "moneyInLabel", placeholder: "nome da receita" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label", for: "moneyInDescription" %>
    <%= form.text_field :description, class: "form-control", id: "moneyInDescription", placeholder: "descrição da receita" %>
  </div>

  <div class="mb-3">
    <%= form.label :amount, class: "form-label", for: "moneyInAmount" %>
    <%= form.number_field :amount, class: "form-control", id: "moneyInAmount", step: "0.01", placeholder: "valor da receita" %>
  </div>
  
  <div class="mb-3">
    <%= form.label :money_date, class: "form-label", for: "moneyInMoneyDate" %>
    <%= form.date_field :money_date, class: "form-control", id: "moneyInMoneyDate" %>
  </div>

  <div class="mb-3">
    <%= form.label :category_id, class: "form-label", for: "moneyInCategoryId" %>
    <%= form.select :category_id, Category.all.collect { |c| [c.name, c.id] }, { include_blank: "Selecione uma categoria" }, class: "form-control", id: "moneyInCategoryId" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Enviar", class: "btn btn-success" %>
  </div>
<% end %>

app/views/money_ins/_money_in.html.erb
<div class="card text-center" id="<%= dom_id money_in %>">
  <div class="card-header">
    <%= money_in.label %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= money_in.description %></p>
  </div>
  <div class="card-body">
    <p class="card-text"><b>Categoria:</b> <%= money_in.category.name %></p>
  </div>
  <div class="card-body">
    <p class="card-text"><b>Valor:</b> R$<%= money_in.amount %></p>
  </div>
  <div class="card-footer text-body-secondary">
    <b><%= money_in.money_date.strftime("%d/%m/%Y") %></b>
  </div>
</div>

app/views/money_ins/edit.html.erb
<% content_for :title, "Editing money in" %>

<h1>Editando Receitas</h1>

<%= render "form", money_in: @money_in %>

<br>

<div class="d-grid gap-3 d-md-block d-md-flex mt-4">
  <%= link_to "Mostrar esta receita", @money_in, class: "btn btn-primary" %>
  <%= link_to "Voltar para receitas", money_ins_path, class: "btn btn-secondary" %>
  <%= button_to "Excluir esta Receita", @money_in, method: :delete, class: "btn btn-danger" %>
</div>

app/views/money_ins/index.html.erb
<% if notice.present? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% content_for :title, "Receitas" %>

<h1>Receitas</h1>
<div class="mb-4">
  <%= search_form_for @q do |f| %>

    <%= f.label :label_or_description_cont, "Descrição Ou Nome", class: "form-label" %>
    <%= f.search_field :label_or_description_cont, class: "form-control" %>

    <div class="row mt-2">
      <div class="col-md-6">
        <%= f.label :money_date_gteq, "Data Inicial", class: "form-label" %>
        <%= f.search_field :money_date_gteq, type: :date, class: "form-control" %>
      </div>
      <div class="col-md-6">
        <%= f.label :money_date_lteq, "Data Final", class: "form-label" %>
        <%= f.search_field :money_date_lteq, type: :date, class: "form-control" %>
      </div>
    </div>

    <%= f.label :category_id_eq, "Categoria", class: "form-label" %>
    <%= f.select :category_id_eq, options_from_collection_for_select(@categories, :id, :name, params.dig(:q, :category_id_eq)), { include_blank: "Todas" }, class: "form-select" %>

    <div class="row mt-2">
      <div class="col-md-6">
        <%= f.label :amount_gteq, "Valor Mínimo", class: "form-label" %>
        <%= f.search_field :amount_gteq, type: :number, step: :any, class: "form-control" %>
      </div>
      <div class="col-md-6">
        <%= f.label :amount_lteq, "Valor Máximo", class: "form-label" %>
        <%= f.search_field :amount_lteq, type: :number, step: :any, class: "form-control" %>
      </div>
    </div>

    <%= f.submit "Buscar", class: "btn btn-primary mt-2" %>
  <% end %>
</div>

<div id="money_ins">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Valor</th>
        <th>Data</th>
        <th>Categoria</th>
        <th>Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @money_ins.each do |money_in| %>
        <tr>
          <td><%= money_in.label %></td>
          <td><%= money_in.description %></td>
          <td><%= number_to_currency(money_in.amount) %></td>
          <td><%= money_in.money_date.strftime("%d/%m/%Y") %></td>
          <td><%= money_in.category.name if money_in.category %></td>
          <td>
            <%= link_to "Editar", edit_money_in_path(money_in), class: "btn btn-warning" %>
            <%= link_to "Excluir", money_in, data: { turbo_method: :delete, turbo_confirm: "Tem certeza?" }, class: "btn btn-danger" %>
            <%= link_to(money_in , class: "btn btn-default") do %>
              <i class="fa-solid fa-eye"></i> Ver
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%== @pagy.series_nav(:bootstrap) %>
<%= link_to "Nova receita", new_money_in_path, class: "btn btn-primary" %>

app/views/money_ins/new.html.erb
<% content_for :title, "Nova Receita" %>

<h1>Nova Receita</h1>

<%= render "form", money_in: @money_in %>

app/views/money_ins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @money_in %>

<div class="d-grid gap-3 d-md-block d-md-flex mt-4">
  <%= link_to "Editar esta Receita", edit_money_in_path(@money_in), class: "btn btn-primary" %>
  <%= link_to "Voltar para receitas", money_ins_path, class: "btn btn-secondary" %>
  <%= button_to "Excluir esta Receita", @money_in, method: :delete, class: "btn btn-danger" %>
</div>