config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :money_ins
  resources :money_outs
  resources :categories

  get "dashboard" => "dashboard#index"
  root to: "dashboard#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "My Money" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="My Money">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%= favicon_link_tag "despesas.png", type: "image/png", sizes: "32x32" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
    />
  </head>

  <body>
    <% unless current_page?(new_session_path) || current_page?(new_password_path) %>
      <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
        <div class="container-fluid">
          <%= link_to "Meu Dinheiro", dashboard_path, class: "navbar-brand active", aria: { current: "page" } %>
          <button class="navbar-toggler p-0 border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="navbar-collapse collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to "Despesas", money_outs_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Receitas", money_ins_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Categorias", categories_path, class: "nav-link" %>
              </li>
            </ul>
            <div class="navbar-text">
              <%= button_to "Sair", session_path, method: :delete, class: "btn btn-link nav-link" %>
            </div>
          </div>
        </div>
      </nav>
    <% end %>

    <main>
      <div class="container align-items-center mt-5 pt-5">
          <%= yield %>
      </div>
    </main>
  </body>
</html>